version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: buildAll.cmd
pull_requests:
  do_not_increment_build_number: true
artifacts:
- path: ElectronNET.WebApp\bin\desktop
  name: Desktop
